name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  q_architecture:
    path: ..

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
