name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.9
  either_dart: ^1.0.0
  equatable: ^3.0.0
  flutter:
    sdk: flutter
  get_it: ^9.3.0
  json_annotation: ^4.12.0
  material_ui: ^1.4.0
  q_architecture:
    path: ..

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.14.1

flutter:
  uses-material-design: true
